openapi: 3.0.0

info:
    title: Get Cortex XDR Incident Information
    description: Retrieve detailed incident information from Cortex XDR
    version: "v1"

servers:
    - url: https://api-gpf.xdr.eu.paloaltonetworks.com/v1

paths:
    /incidents:
        post:
            operationId: getCortexXDRIncident
            summary: Get detailed incident information for a specific incident ID.
            parameters:
                - in: path
                  name: incident_id
                  schema:
                      type: string
                  required: true
                  description: The ID of the incident to retrieve information for              
            responses:
                "200":
                    description: Successful response containing incident details
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getIncidentResponse"
                "404":
                    description: Incident not found
                "500":
                    description: Internal server error

components:
    schemas:
        getIncidentResponse:
            type: object
            properties:
                incident_id:
                    type: string
                status:
                    type: string
                severity:
                    type: string
                assignee:
                    type: string
                events:
                    type: array
                    items:
                        type: object
                        properties:
                            event_id:
                                type: string
                            event_type:
                                type: string
                            timestamp:
                                type: string
                            description:
                                type: string
