openapi: 3.0.1
info:
  title: Cortex XDR Incident Manager API
  description: API to retrieve incidents from Cortex XDR.
  version: "1.0.0"
  contact:
    email: support@example.com
servers:
  - url: https://api-gpf.xdr.eu.paloaltonetworks.com/v1   # Replace with your actual Cortex XDR API URL
paths:
  /incidents:
    get:
      summary: Get all incidents from Cortex XDR
      operationId: getIncidents
      tags:
        - Incidents
      parameters:
        - name: limit
          in: query
          description: Number of incidents to retrieve
          required: false
          schema:
            type: integer
            default: 10
        - name: sort
          in: query
          description: Sort incidents by date or severity
          required: false
          schema:
            type: string
            enum: [date, severity]
      responses:
        '200':
          description: List of incidents retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    incident_id:
                      type: string
                      description: Unique ID of the incident
                    severity:
                      type: string
                      description: Severity level of the incident
                    status:
                      type: string
                      description: Current status of the incident
                    description:
                      type: string
                      description: Details about the incident
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
