openapi: 3.0.0
info:
  title: Cortex XDR API
  description: Retrieve detailed incidents from Cortex XDR.
  version: "1.0.0"
servers:
  - url: https://api-gpf.xdr.eu.paloaltonetworks.com
paths:
  /public_api/v1/incidents/get_incidents/:
    get:
      summary: Get All Incidents
      description: Retrieve a list of incidents from Cortex XDR.
      operationId: getAllIncidents
      parameters:
        - name: page
          in: query
          required: false
          description: The page number to retrieve.
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          description: Number of incidents per page.
          schema:
            type: integer
            example: 50
        - name: sort
          in: query
          required: false
          description: Sort order of incidents (e.g., 'asc' or 'desc').
          schema:
            type: string
            example: "desc"
      responses:
        '200':
          description: Successful retrieval of incidents.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: array
                    items:
                      type: object
                      properties:
                        incident_id:
                          type: string
                          description: Unique identifier for the incident.
                        severity:
                          type: string
                          description: Severity level of the incident.
                        status:
                          type: string
                          description: Current status of the incident.
                        creation_time:
                          type: string
                          format: date-time
                          description: Time when the incident was created.
                        last_modified:
                          type: string
                          format: date-time
                          description: Last modification time of the incident.
        '400':
          description: Bad request or invalid parameters.
        '401':
          description: Unauthorized, API key is missing or incorrect.
        '500':
          description: Internal server error.
 
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
 
security:
  - apiKeyAuth: []
