openapi: 3.0.0

info:
  title: FortiAnalyzer Alerts API
  description: Retrieve and manage alerts in FortiAnalyzer
  version: "v1"

servers:
  - url: https://<your-fortianalyzer-url>/api/v2

paths:
  /alerts:
    get:
      operationId: getAlerts
      summary: Retrieve active alerts from FortiAnalyzer
      parameters:
        - in: query
          name: alertType
          schema:
            type: string
          required: false
          description: Filter alerts by type (e.g., malware, intrusion).
        - in: query
          name: status
          schema:
            type: string
            enum: [active, resolved]
          required: false
          description: Filter alerts by their current status.
        - in: query
          name: startTime
          schema:
            type: string
            format: date-time
          required: false
          description: Start time for filtering alerts.
        - in: query
          name: endTime
          schema:
            type: string
            format: date-time
          required: false
          description: End time for filtering alerts.
      responses:
        "200":
          description: A list of alerts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlertResponse"

components:
  schemas:
    AlertResponse:
      type: object
      properties:
        alerts:
          type: array
          items:
            type: object
            properties:
              alertId:
                type: string
                description: Unique identifier of the alert.
              alertType:
                type: string
                description: Type of alert (e.g., intrusion, malware).
              description:
                type: string
                description: Detailed description of the alert.
              status:
                type: string
                description: Status of the alert (e.g., active, resolved).
              timestamp:
                type: string
                format: date-time
                description: When the alert was triggered.
